title: 10 BELOW
baseline: Your playlist operatives
description: All of 10 BELOW best music
baseurl: /
canonicalurl: true
keywords: [Cecil, Static Site Generator, SSG]
author: Ryan Hilty
date:
  format: j F Y
  timezone: Europe/Paris
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: false # Content to the bottom of the sidebar
  theme: grey, white, black,  # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: true # Reverse layout
